[package]
name = "paypal-v2"
version = "0.0.1"
authors = ["Moritz Bischof <moritz.bischof@aleph-alpha.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smart-default = "0.5"
surf = "1"
async-std = "1"
log = "0.4"
simple_logger = "1"
base64 = "0.11"
