[package]
name = "paypal-v2"
version = "0.0.3"
authors = ["Moritz Bischof <moritz.bischof@aleph-alpha.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smart-default = "0.6"
reqwest = { version = "0.10", features = ["json"] }
log = "0.4"
base64 = "0.12"
thiserror = "1.0"
tokio = { version = "0.2", features = ["macros"] }
parking_lot = "0.11"

[features]
production = []